trigger:
- v4.6

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    # Create a directory to store WildFly
    mkdir -p /opt/wildfly

    # Download and extract WildFly
    wget -P /opt/wildfly https://github.com/wildfly/wildfly/releases/download/29.0.1.Final/wildfly-29.0.1.Final.tar.gz
    tar -xzf /opt/wildfly/wildfly-29.0.1.Final.tar.gz -C /opt/wildfly
    ls /opt/wildfly/wildfly-29.0.1.Final -la
    ls /opt/wildfly/wildfly-29.0.1.Final/bin -la

    # Set environment variable for WildFly
    export JBOSS_HOME="/opt/wildfly/wildfly-29.0.1.Final"
    # Verify the installation
    $JBOSS_HOME/bin/standalone.sh --version
  displayName: 'Install WildFly 29.0.1.Final'

- script: |
    # Install MySQL
    sudo apt-get update
    sudo apt-get install mysql-server -y

    # Configure MySQL (e.g., create databases, users, etc.)
    # Use mysql commands here to set up your MySQL environment

    # Start MySQL service
    sudo service mysql start
  displayName: 'Install and Configure MySQL'

- script: |
    # Add your custom configuration steps for WildFly
    # For example, deploying your application to WildFly
  displayName: 'Custom Configuration Steps for WildFly'

- script: |
    # Add your custom configuration steps for MySQL
    # For example, creating databases and configuring access
  displayName: 'Custom Configuration Steps for MySQL'

- task: Ant@1
  inputs:
    buildFile: 'lams_build/build.xml'
    targets: 'deploy-lams'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
  displayName: 'Run Ant Task'

# Add more steps if needed
